### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by athul** [abhijithneilabraham/kat_ran_thru_my_keebord#8]
I tried this package and wrote this 
```python
from katran import kat
kat.main("./cats")
```
When I run this I get this error.  I tried running `pip3 install AppKit` but it too throws me an error
```bash
$ python3 cats.py
Do you wanna let your cat run on your keyboard? say yes or no
yes
Well then, let's begin
cat is running through ya keyboard.Press ctrl+c two times to exit
woTraceback (most recent call last):
  File "cats.py", line 2, in <module>
    kat.main("./cats")
  File "/usr/local/lib/python3.7/site-packages/katran/kat.py", line 44, in main
    katran(path)
  File "/usr/local/lib/python3.7/site-packages/katran/kat.py", line 28, in katran
    playsound(path_to_audio + random.choice(kat_sounds))
  File "/usr/local/lib/python3.7/site-packages/playsound.py", line 55, in _playsoundOSX
    from AppKit     import NSSound
ModuleNotFoundError: No module named 'AppKit'
```

**Comment by athul** [comment]
Plus you've got to update the peerdependency list in PyPi,  I had to install the `playsound` dependency myself. 

The Above error happened in MacOS Mojave and It seems it was an error in `Xcode` and somehow managed to resolve it by `python3 -m easy_install pyobjc`

**Comment by mcorderoaraya** [comment]
xcode-select --install
brew remove portaudio
brew install portaudio
pip3 install pyaudio

pip3 install --global-option='build_ext' --global-option='-I/usr/local/include' --global-option='-L/usr/local/lib' pyaudio

python3 -m easy_install pyobjc
